name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dennis199441/codingdaily-nginx:latest
    - name: Publish Docker image
      run: docker push dennis199441/codingdaily-nginx:latest
